name: test delete branch

on:
  delete:
    branches:
      - hotfix/*
      - epic/*

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: deleted branch
      run: echo 'deleted ${{ github.event.ref }}' 
